name: PlayerInspectionTools
version: '${project.version}'
main: net.quadseed.minecraft.playerinspectiontools.PlayerInspectionTools
api-version: 1.17
authors: [ quadseed ]
description: Player Inspection Tools for PaperMC Server
