
name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ./target/PlayerInspectionTools-1.0-SNAPSHOT.jar

  update_release_draft:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        id: download_artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: ./

      - name: Make Release Draft
        id: release_draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disable-autolabeler: true

      - name: Upload Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_draft.outputs.upload_url }}
          asset_path: PlayerInspectionTools-1.0-SNAPSHOT.jar
          asset_name: PlayerInspectionTools.jar
          asset_content_type: application/java-archive

